app_name = "Sistema de Ventas v1.0 | Desarrollado por Gluonico"
app_title = "Sistema de Ventas e Inventario - Texaco 31"
company_name = "Estación de Servicio Texaco 31"
button_logout_text = "Salir"
welcome_date_hour_text_bar = "Bienvenido al sistema de ventas e inventario\t\t Fecha: DD-MM-YYYY\t\t Hora: HH:MM:SS"
footer_text = "Sistema de Ventas e Inventario v1.0 | Desarrollado por Gluonico\nContacto: +57 3003943675 - www.gluonico.com"

generic_menu = "Menú"
generic_employees = "Empleados"
generic_employee = "Empleado"
generic_suppliers = "Proveedores"
generic_supplier = "Proveedor"
generic_category = "Categoria"
generic_categories = "Categorias"
generic_product = "Productos"
generic_sales = "Ventas"
generic_exit = "Salir"
generic_save = "Guardar"
generic_add = "Agregar"
generic_update = "Actualizar"
generic_delete = "Eliminar"
generic_clear = "Limpiar"

generic_select = "Seleccionar"
generic_email = "Email"
generic_name = "Nombre"
generic_contact = "Contacto"
generic_search = "Buscar"
generic_gender = "Sexo"
generic_male = "Masculino"
generic_female = "Femenino"
generic_other = "Otro"
generic_birth = "F_Nacimiento"
generic_join_date = "F_Ingreso"
generic_password = "Password"
generic_user_type = "T_Usuario"
generic_admin = "Administrador"
generic_salary = "Salario"
generic_address = "Dirección"
generic_description = "Descripción"
generic_invoice = "Factura"
generic_price = "Precio"
generic_quantity = "Cantidad"
generic_status = "Estado"
generic_empty = "Vacio"
generic_updated = "Actualizado"
generic_confirm = "Confirmar"
generic_added = "Añadido"
generic_deleted = "Eliminado"

generic_active = "Activo"
generic_inactive = "Inactivo"

generic_total_employee = "Total Empleados"
generic_total_supplier = "Total Proveedores"
generic_total_category = "Total Categorias"
generic_total_product = "Total Productos"
generic_total_sales = "Total Ventas"

search_employee = "Buscar Empleado"
search_product = "Buscar Producto"

employee_details = "Detalles del Empleado"
employee_id = "ID"

supplier_details = "Detalles del Proveedor"
invoice_number = "Factura No."

manage_product_category = "Administrar Categoria de Producto"
enter_category_name ="Ingresa nombre de la Categoría"
generic_CID = "CID"

product_details = "Detalles de Producto"
product_id = "ID"

employee_required_id_error = "Se requiere el ID del empleado."
employee_added = "Empleado añadido con éxito."
employee_updated = "Empleado actualizado con éxito."
employee_already_exist = "Este ID de empleado ya existe. Intenta nuevamente."
employee_confirm_delete = "¿Desea eliminar este empleado?"
employee_deleted = "Empleado eliminado con éxito"

generic_success = "Éxito"

search_by_option_message = "Selecciona una opción para buscar."
search_input_required = "Se requiere la información a buscar."
search_no_record_found = "Ningún registro encontrado."